name: Build - Windows

on: workflow_dispatch

env:
  # Path to the solution file relative to the root of the project
  SOLUTION_FILE_PATH: make\mp4muxer\windows_amd64\mp4muxer_2022.vcxproj

  # Configuration type to build
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      with:
        msbuild-architecture: x64

    - name: Build
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 /t:Rebuild
